// This file is ported from src/math/big/ftoa.go in Go 1.26.1.
// Original copyright notice follows:

// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements Float-to-string conversion functions.
// It is closely following the corresponding implementation
// in strconv/ftoa.go, but modified and simplified for Float.

#include "godot_big_decimal.h"
#include "godot_big_float.h"

using namespace godot;

// Text converts the floating-point number x to a string according
// to the given format and precision prec. The format is one of:
//
//	'e'	-d.dddde±dd, decimal exponent, at least two (possibly 0) exponent digits
//	'E'	-d.ddddE±dd, decimal exponent, at least two (possibly 0) exponent digits
//	'f'	-ddddd.dddd, no exponent
//	'g'	like 'e' for large exponents, like 'f' otherwise
//	'G'	like 'E' for large exponents, like 'f' otherwise
//	'x'	-0xd.dddddp±dd, hexadecimal mantissa, decimal power of two exponent
//	'p'	-0x.dddp±dd, hexadecimal mantissa, decimal power of two exponent (non-standard)
//	'b'	-ddddddp±dd, decimal mantissa, decimal power of two exponent (non-standard)
//
// For the power-of-two exponent formats, the mantissa is printed in normalized form:
//
//	'x'	hexadecimal mantissa in [1, 2), or 0
//	'p'	hexadecimal mantissa in [½, 1), or 0
//	'b'	decimal integer mantissa using x.Prec() bits, or 0
//
// Note that the 'x' form is the one used by most other languages and libraries.
//
// If format is a different character, Text returns a "%" followed by the
// unrecognized format character.
//
// The precision prec controls the number of digits (excluding the exponent)
// printed by the 'e', 'E', 'f', 'g', 'G', and 'x' formats.
// For 'e', 'E', 'f', and 'x', it is the number of digits after the decimal point.
// For 'g' and 'G' it is the total number of digits. A negative precision selects
// the smallest number of decimal digits necessary to identify the value x uniquely
// using x.Prec() mantissa bits.
// The prec value is ignored for the 'b' and 'p' formats.
//
// String formats x like x.Text('g', 10).
// (String must be called explicitly, [Float.Format] does not support %s verb.)
//
// Append appends to buf the string form of the floating-point number x,
// as generated by x.Text, and returns the extended buffer.
String BigFloat::String(Format p_format, int64_t p_prec) const {
	PackedByteArray buf;

	// sign
	if (_neg) {
		buf.append('-');
	}

	// Inf
	if (_form == FORM_INF) {
		if (!_neg) {
			buf.append('+');
		}
		buf.append_array({ 'I', 'n', 'f' });
		return buf.get_string_from_ascii();
	}

	// pick off easy formats
	switch (p_format) {
		case FORMAT_DECIMAL:
			return _fmtB(buf);
		case FORMAT_HEX_NORMAL:
			return _fmtP(buf);
		case FORMAT_HEX:
			return _fmtX(buf, p_prec);
		default:
			break;
	}

	// Algorithm:
	//   1) convert Float to multiprecision decimal
	//   2) round to desired precision
	//   3) read digits out and format

	// 1) convert Float to multiprecision decimal
	BigDecimal d; // == 0.0
	if (_form == FORM_FINITE) {
		// x != 0
		d.init(_mant, static_cast<int64_t>(_exp) - _mant.bitLen());
	}

	// 2) round to desired precision
	bool shortest = false;
	if (p_prec < 0) {
		shortest = true;
		d.roundShortest(this);
		// Precision for shortest representation mode.
		switch (p_format) {
			case FORMAT_SCIENTIFIC:
			case FORMAT_SCIENTIFIC_UPPER:
				p_prec = d.mant.size() - 1;
				break;
			case FORMAT_PLAIN:
				p_prec = MAX(d.mant.size() - d.exp, 0);
				break;
			case FORMAT_AUTO:
			case FORMAT_AUTO_UPPER:
				p_prec = d.mant.size();
				break;
			default:
				break;
		}
	} else {
		// round appropriately
		switch (p_format) {
			case FORMAT_SCIENTIFIC:
			case FORMAT_SCIENTIFIC_UPPER:
				// one digit before and number of digits after decimal point
				d.round(1 + p_prec);
				break;
			case FORMAT_PLAIN:
				// number of digits before and after decimal point
				d.round(d.exp + p_prec);
				break;
			case FORMAT_AUTO:
			case FORMAT_AUTO_UPPER:
				if (p_prec == 0) {
					p_prec = 1;
				}
				d.round(p_prec);
				break;
			default:
				break;
		}
	}

	// 3) read digits out and format
	switch (p_format) {
		case FORMAT_SCIENTIFIC:
		case FORMAT_SCIENTIFIC_UPPER:
			return _fmtE(buf, p_format, p_prec, d);
		case FORMAT_PLAIN:
			return _fmtF(buf, p_prec, d);
		case FORMAT_AUTO:
		case FORMAT_AUTO_UPPER: {
			// trim trailing fractional zeros in %e format
			int64_t eprec = p_prec;
			if (eprec > d.mant.size() && d.mant.size() >= d.exp) {
				eprec = d.mant.size();
			}

			// %e is used if the exponent from the conversion
			// is less than -4 or greater than or equal to the precision.
			// If precision was the shortest possible, use eprec = 6 for
			// this decision.
			if (shortest) {
				eprec = 6;
			}

			const int64_t exp = d.exp - 1;
			if (exp < -4 || exp >= eprec) {
				return _fmtE(buf, static_cast<Format>(p_format + 'e' - 'g'), MIN(p_prec, d.mant.size()) - 1, d);
			}

			if (p_prec > d.exp) {
				p_prec = d.mant.size();
			}

			return _fmtF(buf, MAX(p_prec - d.exp, 0), d);
		}
		default:
			ERR_FAIL_V_MSG(vformat("%%%c", p_format), "unknown format");
	}
}

void BigDecimal::roundShortest(const BigFloat *p_x) {
	// if the mantissa is zero, the number is zero - stop now
	if (mant.is_empty()) {
		return;
	}

	// Approach: All numbers in the interval [x - 1/2ulp, x + 1/2ulp]
	// (possibly exclusive) round to x for the given precision of x.
	// Compute the lower and upper bound in decimal form and find the
	// shortest decimal number d such that lower <= d <= upper.

	// TODO(gri) strconv/ftoa.do describes a shortcut in some cases.
	// See if we can use it (in adjusted form) here as well.

	// 1) Compute normalized mantissa mant and exponent exp for x such
	// that the lsb of mant corresponds to 1/2 ulp for the precision of
	// x (i.e., for mant we want x.prec + 1 bits).
	BigNat m;
	m.set(p_x->_mant);
	int64_t exp = int64_t(p_x->_exp) - m.bitLen();
	int64_t s = m.bitLen() - static_cast<int64_t>(p_x->_prec + 1);
	if (s < 0) {
		m.lsh(m, static_cast<uint64_t>(-s));
	} else if (s > 0) {
		m.rsh(m, static_cast<uint64_t>(+s));
	}
	exp += s;
	// x = mant * 2**exp with lsb(mant) == 1/2 ulp of x.prec

	// 2) Compute lower bound by subtracting 1/2 ulp.
	BigDecimal lower;
	BigNat tmp;
	tmp.sub1(m);
	lower.init(tmp, exp);

	// 3) Compute upper bound by adding 1/2 ulp.
	BigDecimal upper;
	tmp.add1(m);
	upper.init(tmp, exp);

	// The upper and lower bounds are possible outputs only if
	// the original mantissa is even, so that ToNearestEven rounding
	// would round to the original mantissa and not the neighbors.
	const bool inclusive = (m[0] & 2) == 0; // test bit 1 since original mantissa was shifted by 1

	// Now we can figure out the minimum number of digits required.
	// Walk along until d has distinguished itself from upper and lower.
	for (int64_t i = 0; i < mant.size(); i++) {
		const char m = mant[i];
		const char l = lower.at(i);
		const char u = upper.at(i);

		// Okay to round down (truncate) if lower has a different digit
		// or if lower is inclusive and is exactly the result of rounding
		// down (i.e., and we have reached the final digit of lower).
		const bool okdown = l != m || (inclusive && i + 1 == lower.mant.size());

		// Okay to round up if upper has a different digit and either upper
		// is inclusive or upper is bigger than the result of rounding up.
		const bool okup = m != u && (inclusive || m + 1 < u || i + 1 < upper.mant.size());

		// If it's okay to do either, then round to the nearest one.
		// If it's okay to do only one, do it.
		if (okdown && okup) {
			round(i + 1);
			return;
		}

		if (okdown) {
			roundDown(i + 1);
			return;
		}

		if (okup) {
			roundUp(i + 1);
			return;
		}
	}
}

// %e: d.ddddde±dd
String BigFloat::_fmtE(PackedByteArray &buf, Format fmt, int64_t prec, BigDecimal &d) {
	// first digit
	char ch = '0';
	if (!d.mant.is_empty()) {
		ch = d.mant[0];
	}
	buf.append(ch);

	// .moredigits
	if (prec > 0) {
		buf.append('.');
		int64_t i = 1;
		int64_t m = Math::min(d.mant.size(), prec + 1);
		if (i < m) {
			buf.append_array(d.mant.slice(i, m));
			i = m;
		}
		for (; i <= prec; i++) {
			buf.append('0');
		}
	}

	// e±
	buf.append(fmt);
	int64_t exp = 0;
	if (!d.mant.is_empty()) {
		exp = d.exp - 1; // -1 because first digit was printed before '.'
	}
	if (exp < 0) {
		ch = '-';
		exp = -exp;
	} else {
		ch = '+';
	}
	buf.append(ch);

	// dd...d
	if (exp < 10) {
		buf.append('0'); // at least 2 exponent digits
	}

	return vformat("%s%d", buf.get_string_from_ascii(), exp);
}

// %f: ddddddd.ddddd
String BigFloat::_fmtF(PackedByteArray &buf, int64_t prec, BigDecimal &d) {
	// integer, padded with zeros as needed
	if (d.exp > 0) {
		int64_t m = Math::min(d.mant.size(), d.exp);
		buf.append_array(d.mant.slice(0, m));
		for (; m < d.exp; m++) {
			buf.append('0');
		}
	} else {
		buf.append('0');
	}

	// fraction
	if (prec > 0) {
		buf.append('.');
		for (int64_t i = 0; i < prec; i++) {
			buf.append(d.at(d.exp + i));
		}
	}

	return buf.get_string_from_ascii();
}

// fmtB appends the string of x in the format mantissa "p" exponent
// with a decimal mantissa and a binary exponent, or "0" if x is zero,
// and returns the extended buffer.
// The mantissa is normalized such that is uses x.Prec() bits in binary
// representation.
// The sign of x is ignored, and x must not be an Inf.
// (The caller handles Inf before invoking fmtB.)
String BigFloat::_fmtB(PackedByteArray &buf) const {
	if (_form == FORM_ZERO) {
		buf.append('0');
		return buf.get_string_from_ascii();
	}

	DEV_ASSERT(_form == FORM_FINITE);
	// x != 0

	// adjust mantissa to use exactly x.prec bits
	BigNat m = _mant;
	uint32_t w = static_cast<uint32_t>(m.array.size() * 64);
	if (w < _prec) {
		m.lsh(m, _prec - w);
	} else if (w > _prec) {
		m.rsh(m, w - _prec);
	}

	buf.append_array(m.utoa(10).to_ascii_buffer());
	buf.append('p');
	int64_t e = static_cast<int64_t>(_exp) - static_cast<int64_t>(_prec);
	if (e >= 0) {
		buf.append('+');
	}
	return vformat("%s%d", buf.get_string_from_ascii(), e);
}

// fmtX appends the string of x in the format "0x1." mantissa "p" exponent
// with a hexadecimal mantissa and a binary exponent, or "0x0p0" if x is zero,
// and returns the extended buffer.
// A non-zero mantissa is normalized such that 1.0 <= mantissa < 2.0.
// The sign of x is ignored, and x must not be an Inf.
// (The caller handles Inf before invoking fmtX.)
String BigFloat::_fmtX(PackedByteArray &buf, int64_t prec) const {
	if (_form == FORM_ZERO) {
		buf.append_array({ '0', 'x', '0' });
		if (prec > 0) {
			buf.append('.');
			for (int64_t i = 0; i < prec; i++) {
				buf.append('0');
			}
		}
		buf.append_array({ 'p', '+', '0', '0' });
		return buf.get_string_from_ascii();
	}

	DEV_ASSERT(_form == FORM_FINITE);

	// round mantissa to n bits
	uint64_t n = 0;
	if (prec < 0) {
		n = 1 + ((MinPrec() - 1 + 3) / 4 * 4); // round MinPrec up to 1 mod 4
	} else {
		n = 1 + (4 * static_cast<uint64_t>(prec));
	}
	// n%4 == 1
	Ref<BigFloat> x{ memnew(BigFloat) };
	x->SetPrec(n);
	x->SetMode(_mode);
	x->Set(const_cast<BigFloat *>(this));

	// adjust mantissa to use exactly n bits
	BigNat m = x->_mant;
	const uint64_t w = m.array.size() * 64;
	if (w < n) {
		m.lsh(m, n - w);
	} else if (w > n) {
		m.rsh(m, w - n);
	}
	int64_t exp64 = static_cast<int64_t>(_exp) - 1; // avoid wrap-around

	const godot::String hm = m.utoa(16);
	DEV_ASSERT(hm[0] == '1');
	buf.append_array({ '0', 'x', '1' });
	if (hm.length() > 1) {
		buf.append('.');
		buf.append_array(hm.substr(1).to_ascii_buffer());
	}

	buf.append('p');
	if (exp64 >= 0) {
		buf.append('+');
	} else {
		exp64 = -exp64;
		buf.append('-');
	}
	// Force at least two exponent digits, to match fmt.
	if (exp64 < 10) {
		buf.append('0');
	}
	return vformat("%s%d", buf.get_string_from_ascii(), exp64);
}

// fmtP appends the string of x in the format "0x." mantissa "p" exponent
// with a hexadecimal mantissa and a binary exponent, or "0" if x is zero,
// and returns the extended buffer.
// The mantissa is normalized such that 0.5 <= 0.mantissa < 1.0.
// The sign of x is ignored, and x must not be an Inf.
// (The caller handles Inf before invoking fmtP.)
String BigFloat::_fmtP(PackedByteArray &buf) const {
	if (_form == FORM_ZERO) {
		buf.append('0');
		return buf.get_string_from_ascii();
	}

	DEV_ASSERT(_form == FORM_FINITE);
	// x != 0

	// remove trailing 0 words early
	// (no need to convert to hex 0's and trim later)
	BigNat m = _mant;
	int64_t i = 0;
	while (i < m.array.size() && m[i] == 0) {
		i++;
	}
	m.array = m.array.slice(i);

	buf.append_array({ '0', 'x', '.' });
	buf.append_array(m.utoa(16).rstrip("0").to_ascii_buffer());
	buf.append('p');
	if (_exp >= 0) {
		buf.append('+');
	}

	return vformat("%s%d", buf.get_string_from_ascii(), _exp);
}
